version: '3.8'

services:
  # Backend API
  backend-api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: biometric-did-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - API_SECRET_KEY=${API_SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRATION_HOURS=${JWT_EXPIRATION_HOURS:-24}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - RATE_LIMIT_ENABLED=true
      - AUDIT_LOG_ENABLED=true
      - HTTPS_ONLY=${HTTPS_ONLY:-false}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - biometric-did-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Demo Wallet (Frontend)
  demo-wallet:
    build:
      context: ./demo-wallet
      dockerfile: Dockerfile
    container_name: biometric-did-wallet
    restart: unless-stopped
    ports:
      - "3003:80"
    environment:
      - VITE_API_URL=${API_URL:-https://api.biometric-did.example.com}
    networks:
      - biometric-did-network
    depends_on:
      - backend-api

  # Nginx Reverse Proxy (optional, for production SSL/TLS)
  nginx:
    image: nginx:alpine
    container_name: biometric-did-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - biometric-did-network
    depends_on:
      - backend-api
      - demo-wallet
    profiles:
      - production  # Only start in production mode

networks:
  biometric-did-network:
    driver: bridge

volumes:
  logs:
  data:
